version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana-spg
    env_file:
      - ./docker/grafana.env
    ports:
      - "3000:3000"
    networks:
      - net
    depends_on:
      - prometheus
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager-spg
    volumes:
      - ./docker/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - net
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus-spg
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9090:9090"
    networks:
      - net
    depends_on:
      - spgapp
  spgapp:
    # build and start spring application inside a separate container using the same network as prometheus
    image: spring-prometheus-grafana
    container_name: springboot-app-spg
    ports:
      - "8080:8080"
    networks:
      - net
networks:
  net:
